CREATE TABLE IF NOT EXISTS beds (
  id VARCHAR(36) PRIMARY KEY,
  number VARCHAR(20) NOT NULL UNIQUE,
  floor INT NOT NULL,
  ward VARCHAR(80) NOT NULL,
  type VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL
);
