spring:
  application:
    name: medicore-hms
  datasource:
    url: jdbc:mysql://localhost:3306/medicore_hms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        envers:
          store_data_at_delete: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: info

app:
  security:
    jwt:
      secret: c3VwZXItc2VjdXJlLXNlY3JldC1rZXktZm9yLW1lZGljb3JlLWhtcy0yMDI2
      access-token-minutes: 15
      refresh-token-days: 7
